project:
  type: website

website:
  title: "Map"
  navbar:
    right:
      - icon: github
        href: https://github.com/safiyasirota/mta_challenge
    left: 
      - text: "Code"
        href: eda.qmd

format:
  html:
    theme: slate
    fontcolor: "white"
    mainfont: "Courier New"
    linkcolor: "pink"
    css: styles.css
    toc: false